### PR TITLE
Fix typo in 'Great Britain' and add documentation strings

### PR DESCRIPTION
**Pull request by danielhjames**
This change was tested on my local build, it seems to work OK.

### CODE REVIEW

**Comment by pgundlach** [comment]
Thank you very much!

**Comment by pgundlach** [comment]
BTW: don't edit `layoutschema-en.rng` as it is generated from commands.xml with `rake schema`. I have copied your documentation strings to `commands.xml`.

**Comment by danielhjames** [comment]
Thanks for the tip, I saw the similarity but guessed in the wrong direction :-)

**Comment by pgundlach** [comment]
Next time you have the question: look at the first line. If it reads `<!--Do not edit this file. ...` you are in the wrong file ;-)

**Pull request merged**
