### PR TITLE
Fix behaviour of <Nobreak reduce="fontsize">

### PR DESCRIPTION
**Pull request by iclukas**
Also fix `<Nobreak reduce="cut">` while we’re at it.

### CODE REVIEW

**Comment by pgundlach** [comment]
This is really good Thank you so much! 

Could you (please) create a pull request against current develop? The master branch is out of date and should be removed. Devlopment is done on develop.

**Comment by pgundlach** [comment]
(I see that you have taken the develop branch, but I wonder why so many commits are included in your pull request..)

**Comment by iclukas** [comment]
Possibly because I cloned the repository with PHPStorm. Should I try again?

**Comment by pgundlach** [comment]
If you don't mind then yes. Otherwise I would create a commit and mention you in the commit message.

**Pull request closed without merging**
