### PR TITLE
New option --prepend-xml

### PR DESCRIPTION
**Pull request by iclukas**

### CODE REVIEW

**Comment by neolithos** [comment]
What is the idea behind this option?

**Comment by pgundlach** [comment]
The idea is to have code executed before the `layout.xml` file is read.

**Comment by neolithos** [comment]
Is this useful for a cooperated design?

**Comment by pgundlach** [comment]
I'd say it has very limited uses in very special cases. There was already an option to load multiple XML layout files, but this changes only the order of inclusion. The idea is to separate page types, font loading and other stuff in smaller files. Perhaps it is useful for colaboration, but I have never used it that way.

**Comment by neolithos** [comment]
Thx. And have a nice weekend.

**Pull request merged**
