### PR TITLE
add example url

### PR DESCRIPTION
**Pull request by pr-apes**

### CODE REVIEW

**Comment by pr-apes** [comment]
I  have just realized that there is also documentation in German.

Sorry, but I cannot provide a PR for German.

**Comment by pgundlach** [comment]
I have no idea how to merge a patch and change it without messing up the timeline. I have added your patch. Thank you very much!

**Comment by pr-apes** [comment]
It is fine for me.

But was my PR in a different timezone than CEST?

I modified the file using the web editor from _GitHub_ right before submitting the pull request.

**Comment by pgundlach** [comment]
I am not a git wizard, my timeline sometimes looks messed up when I merge (I usually have local changes that need to be part of the tree as well) - so I believe your edit was correct.

**Pull request closed without merging**
