### PR TITLE
adds `border-radius` to `<Frame>`

### PR DESCRIPTION
**Pull request by pr-apes**
enables a single `border-radius` attribute for `<Frame>`

### CODE REVIEW

**Comment by pr-apes** [comment]
This comes from #459 (in a certain sense).

I think this:

``` xml
<Frame framecolor="black" rulewidth="1pt" border-radius="7pt">
```

is better (or at least shorter) than this:

``` xml
<Frame framecolor="black" rulewidth="1pt"
  border-top-left-radius="7pt"
  border-top-right-radius="7pt"
  border-bottom-left-radius="7pt"
  border-bottom-right-radius="7pt">
```

If you agree, other attributes might be simplified this way.

**Comment by pgundlach** [comment]
Thank you very much!


I have added these changes to `commands.xml`, so `rake schema` updates the four schema files and the documentation:

```diff
diff --git a/doc/commands-xml/commands.xml b/doc/commands-xml/commands.xml
index 8201e1c0..7a638cdc 100644
--- a/doc/commands-xml/commands.xml
+++ b/doc/commands-xml/commands.xml
@@ -3412,6 +3412,14 @@
         <para>Radius der Ecke unten links.</para>
       </description>
     </attribute>
+    <attribute en="border-radius" optional="yes" since="4.13.14">
+      <description xml:lang="en">
+        <para>Border rdius of the four corners.</para>
+      </description>
+      <description xml:lang="de">
+        <para>Radien aller vier Ecken.</para>
+      </description>
+    </attribute>
     <attribute en="framecolor" type="text" optional="yes">
       <description xml:lang="en">
         <para>The color of the frame around the object. Only makes sense in combination with the attribute 'frame'.</para>
```

**Comment by pr-apes** [comment]
Sorry, I forgot that the source was `commands.xml`.

BTW,  there is a small typo (I hand edited to display _r<b>a</b>dius_ [_a_ is missing there]).

``` diff
diff --git a/doc/commands-xml/commands.xml b/doc/commands-xml/commands.xml
index 8201e1c0..7a638cdc 100644
--- a/doc/commands-xml/commands.xml
+++ b/doc/commands-xml/commands.xml
@@ -3412,6 +3412,14 @@
       </description>
     </attribute>
    <attribute en="border-radius" optional="yes" since="4.13.14">
      <description xml:lang="en">
-        <para>Border rdius of the four corners.</para>
+        <para>Border radius of the four corners.</para>
      </description>
      <description xml:lang="de">
        <para>Radien aller vier Ecken.</para>

```

**Comment by pr-apes** [comment]
Sorry, the new commits weren't intended until this commit was solved.

But it seems that GitHub adds new commits to an open PR when the forked version has new pushed commits in the same branch where the original commits from the PR come from.

BTW, `<Image margin="">` depends on #491 being fixed (sorry for not providing a patch, but I don't know what is wrong here).

**Comment by pgundlach** [comment]
Added with 7ec5e7ae1b1b6c4858039463fb09eefa3bd1e1e2

Thank you very much!

**Pull request closed without merging**
